[Interface]
PrivateKey = yASkU3Mw5SfwU3eLk+jecj8Pa2Wb/UUu9vaB4/ZV9VM=
Address = 10.104.0.14/32
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = YLaLJahXZ6NuASXQLPl0eUPVAypirpaLuuO7tZa2bmo=
Endpoint = 147.135.15.16:443
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
