[Interface]
PrivateKey = YFxkLlfcVFxCktXeFIhD6KmZrczQI+nnBJSr1Acm6X4=
Address = 10.104.1.103/32
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = Rn6w1t6actF9XC0bMIXxO25rf31uFqm2/n5sYyK1UzQ=
Endpoint = 147.135.37.178:443
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
